#spring.application.name=mailsender
spring:
  application:
    name: mailsender
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@email.com
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

